---
roles:
  hosts:
    provisioners:
      - {type: hosts}

  2_cpus:
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--cpus', 2]

  auto_net:
    private_networks:
      - ip: '0.0.0.0'
        auto_network: true

  puppet_master:
    provisioners:
      - type: pe_bootstrap
        role: :master
        answer_extras:
          - "q_puppetmaster_r10k_remote='ssh://git@bitbucket:7999/pupp/control-repo.git'"
          - "q_puppetmaster_r10k_private_key=/opt/puppetlabs/puppetserver/ssh/id-control_repo.rsa"
          - "q_puppetmaster_code_manager_auto_configure=y"
          - "q_puppetmaster_file_sync_service_enabled=y"

  setup_control_repo:
    provisioners:
      - type: shell
        inline: "yes | cp /vagrant/environment.conf /etc/puppetlabs/code/environments/production/environment.conf"
      - type: shell
        inline: "yes | cp -r /vagrant/manifests /etc/puppetlabs/code/environments/production/"
      - type: shell
        inline: "yes | cp -r /vagrant/site /etc/puppetlabs/code/environments/production/"
      - type: shell
        inline: "yes | cp -r /vagrant/scripts /etc/puppetlabs/code/environments/production/"

  get_modules:
    provisioners:
      - type: shell
        inline: "/opt/puppetlabs/bin/puppet module install puppetlabs-inifile --modulepath /etc/puppetlabs/code/modules"
      - type: shell
        inline: "/opt/puppetlabs/bin/puppet module install puppetlabs-java_ks --modulepath /etc/puppetlabs/code/modules"
      - type: shell
        inline: "/opt/puppetlabs/bin/puppet module install abrader-gms --modulepath /etc/puppetlabs/code/modules"
      - type: shell
        inline: "/opt/puppetlabs/bin/puppet module install pltraining-rbac --modulepath /etc/puppetlabs/code/modules"
      - type: shell
        inline: "/opt/puppetlabs/bin/puppet module install stahnma-epel --modulepath /etc/puppetlabs/code/modules"
      - type: shell
        inline: "/opt/puppetlabs/bin/puppet module install puppet-archive --modulepath /etc/puppetlabs/code/modules"
      - type: shell
        inline: "/bin/chown -R pe-puppet:pe-puppet /etc/puppetlabs/code/modules"

  puppet_agent:
    provisioners:
      - type: pe_agent
        master_vm: 'puppet-master'

  windows_base:
    communicator: "winrm"
    forwarded_ports:
      - { guest: 5985, host: 5986 }
      - { guest: 3389, host: 3390 }

  windows_agent_372:
    guest: windows
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: pe_bootstrap
        version: '3.7.2'
        master: 'master372-centos'

  posix_agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}

  no_pe:
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}

  el-tools:
    provisioners:
      - type: shell
        inline: '/usr/bin/yum install telnet vim tree git -y'

  customize_pe_via_hiera:
    provisioners:
      - type: shell
        inline: 'mkdir -p /var/lib/hiera; cp /vagrant/config/hierafiles/defaults.yaml /var/lib/hiera/defaults.yaml'



