---
vms:
  - name: "puppet-master"
    box:  "puppetlabs/centos-7.2-64-nocm"
    roles: [ "stash", "puppet_master", "customize_pe_via_hiera", "centos7", "hosts", "4gb-memory", "auto_net" ]

  - name: "stash-server"
    box:  "puppetlabs/centos-7.2-64-nocm"
    roles: [ "posix_agent", "puppet_agent", "centos7", "1gb-memory", "2_cpus" ]

